name: test

# run when `dev` has a push or PR
# or when `master` has a push
on:
  pull_request:
    types:
      - opened
    branches:
      - dev
  push:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19.x

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
